"""empty message

Revision ID: 260087357c20
Revises: 
Create Date: 2018-06-29 17:46:32.319645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260087357c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_size', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('purchasability', sa.String(length=50), nullable=True),
    sa.Column('natural_products', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('data_dict', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_date_uploaded'), 'history', ['date_uploaded'], unique=False)
    op.create_index(op.f('ix_history_status'), 'history', ['status'], unique=False)
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_field_name'), 'catalog', ['field_name'], unique=False)
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('status_type', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_log_date'), 'job_log', ['date'], unique=False)
    op.create_index(op.f('ix_job_log_status_type'), 'job_log', ['status_type'], unique=False)
    op.drop_index('ix_task_name', table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='task_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_index('ix_task_name', 'task', ['name'], unique=False)
    op.drop_index(op.f('ix_job_log_status_type'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_date'), table_name='job_log')
    op.drop_table('job_log')
    op.drop_index(op.f('ix_catalog_field_name'), table_name='catalog')
    op.drop_table('catalog')
    op.drop_index(op.f('ix_history_status'), table_name='history')
    op.drop_index(op.f('ix_history_date_uploaded'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
