"""empty message

Revision ID: 0aa00de44f95
Revises: c8c8c17e7c82
Create Date: 2018-05-03 16:43:22.527849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa00de44f95'
down_revision = 'c8c8c17e7c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('status2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_log', 'status2')
    # ### end Alembic commands ###
