"""empty message

Revision ID: 0f8b50870ab3
Revises: 260087357c20
Create Date: 2018-07-02 09:48:49.009445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8b50870ab3'
down_revision = '260087357c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('data_array', sa.Text(), nullable=True))
    op.drop_column('history', 'data_dict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('data_dict', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('history', 'data_array')
    # ### end Alembic commands ###
