"""empty message

Revision ID: 141bf81730c8
Revises: c323fa815f5a
Create Date: 2018-05-18 11:48:53.085932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141bf81730c8'
down_revision = 'c323fa815f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('value2', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_catalog_value2'), 'catalog', ['value2'], unique=False)
    op.drop_index('ix_settings_field_type', table_name='settings')
    op.drop_index('ix_settings_field_type2', table_name='settings')
    op.drop_column('settings', 'field_type2')
    op.drop_column('settings', 'field_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('field_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('field_type2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_settings_field_type2', 'settings', ['field_type2'], unique=False)
    op.create_index('ix_settings_field_type', 'settings', ['field_type'], unique=False)
    op.drop_index(op.f('ix_catalog_value2'), table_name='catalog')
    op.drop_column('catalog', 'value2')
    # ### end Alembic commands ###
