"""empty message

Revision ID: 2c04ba6737bb
Revises: a32a9b5d4732
Create Date: 2018-04-24 13:07:31.429956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c04ba6737bb'
down_revision = 'a32a9b5d4732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_log_date'), 'job_log', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_log_date'), table_name='job_log')
    op.drop_table('job_log')
    # ### end Alembic commands ###
