"""empty message

Revision ID: 37e7f28ba848
Revises: 78455413fd83
Create Date: 2018-05-30 11:25:13.916263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e7f28ba848'
down_revision = '78455413fd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_allowed_value_field_name', table_name='field_allowed_value')
    op.drop_column('field_allowed_value', 'field_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_allowed_value', sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_field_allowed_value_field_name', 'field_allowed_value', ['field_name'], unique=True)
    # ### end Alembic commands ###
