"""empty message

Revision ID: 4ad51533db61
Revises: 
Create Date: 2018-03-07 14:33:17.987224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad51533db61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('logo', sa.String(length=400), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('telephone_number', sa.String(length=40), nullable=True),
    sa.Column('toll_free_number', sa.String(length=40), nullable=True),
    sa.Column('fax_number', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('sales_email', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_address'), 'companies', ['address'], unique=True)
    op.create_index(op.f('ix_companies_date_created'), 'companies', ['date_created'], unique=False)
    op.create_index(op.f('ix_companies_description'), 'companies', ['description'], unique=True)
    op.create_index(op.f('ix_companies_fax_number'), 'companies', ['fax_number'], unique=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_sales_email'), 'companies', ['sales_email'], unique=True)
    op.create_index(op.f('ix_companies_telephone_number'), 'companies', ['telephone_number'], unique=True)
    op.create_index(op.f('ix_companies_toll_free_number'), 'companies', ['toll_free_number'], unique=True)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=True)
    op.create_table('file_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('col_type', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_formats_order'), 'file_formats', ['order'], unique=False)
    op.create_index(op.f('ix_file_formats_title'), 'file_formats', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_date_uploaded'), 'histories', ['date_uploaded'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_histories_date_uploaded'), table_name='histories')
    op.drop_table('histories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_file_formats_title'), table_name='file_formats')
    op.drop_index(op.f('ix_file_formats_order'), table_name='file_formats')
    op.drop_table('file_formats')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_toll_free_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_telephone_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_sales_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_fax_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_description'), table_name='companies')
    op.drop_index(op.f('ix_companies_date_created'), table_name='companies')
    op.drop_index(op.f('ix_companies_address'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
