"""empty message

Revision ID: 6421ebefff8a
Revises: 212d028b1921
Create Date: 2018-05-17 15:27:19.079044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6421ebefff8a'
down_revision = '212d028b1921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'number_of_decimal2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('number_of_decimal2', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
