"""empty message

Revision ID: 6763ef838cbc
Revises: e92b59bb1737
Create Date: 2018-02-28 13:00:05.598587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6763ef838cbc'
down_revision = 'e92b59bb1737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_format', sa.Column('separator', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_format', 'separator')
    # ### end Alembic commands ###
