"""empty message

Revision ID: 6a3da21bf541
Revises: 37e7f28ba848
Create Date: 2018-05-30 11:29:32.866430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3da21bf541'
down_revision = '37e7f28ba848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_string_field_name', table_name='field_string')
    op.drop_table('field_string')
    op.alter_column('field_allowed_value', 'field_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'field_allowed_value', ['field_id'])
    op.drop_index('ix_field_decimal_field_name', table_name='field_decimal')
    op.create_unique_constraint(None, 'field_decimal', ['field_id'])
    op.drop_column('field_decimal', 'field_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_decimal', sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'field_decimal', type_='unique')
    op.create_index('ix_field_decimal_field_name', 'field_decimal', ['field_name'], unique=True)
    op.drop_constraint(None, 'field_allowed_value', type_='unique')
    op.alter_column('field_allowed_value', 'field_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('field_string',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('allowed_values', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='field_string_pkey')
    )
    op.create_index('ix_field_string_field_name', 'field_string', ['field_name'], unique=True)
    # ### end Alembic commands ###
