"""empty message

Revision ID: 71b778d42c49
Revises: 99469e6e8907
Create Date: 2018-05-23 14:18:50.055885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b778d42c49'
down_revision = '99469e6e8907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_decimal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('min_val', sa.Float(), nullable=True),
    sa.Column('max_val', sa.Float(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_decimal_field_name'), 'field_decimal', ['field_name'], unique=True)
    op.create_table('field_integer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('min_val', sa.Integer(), nullable=True),
    sa.Column('max_val', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_integer_field_name'), 'field_integer', ['field_name'], unique=True)
    op.create_table('field_string',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('allowed_values', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_string_field_name'), 'field_string', ['field_name'], unique=True)
    op.alter_column('company', 'job_notify_email',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_job_log_status_type'), 'job_log', ['status_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_log_status_type'), table_name='job_log')
    op.alter_column('company', 'job_notify_email',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_field_string_field_name'), table_name='field_string')
    op.drop_table('field_string')
    op.drop_index(op.f('ix_field_integer_field_name'), table_name='field_integer')
    op.drop_table('field_integer')
    op.drop_index(op.f('ix_field_decimal_field_name'), table_name='field_decimal')
    op.drop_table('field_decimal')
    # ### end Alembic commands ###
