"""empty message

Revision ID: 742cfd33afa5
Revises: 
Create Date: 2018-06-12 14:03:07.862876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742cfd33afa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_field_name'), 'catalog', ['field_name'], unique=False)
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.drop_index('ix_task_model_name', table_name='task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_model_name', 'task', ['name'], unique=False)
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_index(op.f('ix_catalog_field_name'), table_name='catalog')
    op.drop_table('catalog')
    # ### end Alembic commands ###
