"""empty message

Revision ID: 78455413fd83
Revises: 76b2d8378538
Create Date: 2018-05-30 11:21:56.532970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78455413fd83'
down_revision = '76b2d8378538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_field_name'), 'field', ['field_name'], unique=True)
    op.create_table('field_allowed_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('allowed_values', sa.Text(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_allowed_value_field_name'), 'field_allowed_value', ['field_name'], unique=True)
    op.drop_index('ix_field_integer_field_name', table_name='field_integer')
    op.drop_table('field_integer')
    op.add_column('field_decimal', sa.Column('field_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'field_decimal', 'field', ['field_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_decimal', type_='foreignkey')
    op.drop_column('field_decimal', 'field_id')
    op.create_table('field_integer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('min_val', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_val', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='field_integer_pkey')
    )
    op.create_index('ix_field_integer_field_name', 'field_integer', ['field_name'], unique=True)
    op.drop_index(op.f('ix_field_allowed_value_field_name'), table_name='field_allowed_value')
    op.drop_table('field_allowed_value')
    op.drop_index(op.f('ix_field_field_name'), table_name='field')
    op.drop_table('field')
    # ### end Alembic commands ###
