"""empty message

Revision ID: 89c0751e91a2
Revises: 141bf81730c8
Create Date: 2018-05-18 15:09:34.372810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c0751e91a2'
down_revision = '141bf81730c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('field_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'field_type')
    # ### end Alembic commands ###
