"""smiles added to company table

Revision ID: 96ca674efa29
Revises: 16c77dc32c9d
Create Date: 2019-08-20 14:00:22.319359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ca674efa29'
down_revision = '16c77dc32c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('smiles', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'smiles')
    # ### end Alembic commands ###
