"""empty message

Revision ID: a32a9b5d4732
Revises: fc75528b17ff
Create Date: 2018-04-19 14:47:07.529310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32a9b5d4732'
down_revision = 'fc75528b17ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_format', 'mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_format', 'mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
