"""empty message

Revision ID: adfe0bc1db6c
Revises: fd19ac6cacfd
Create Date: 2018-05-03 11:28:30.019527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfe0bc1db6c'
down_revision = 'fd19ac6cacfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('status_type1', sa.Integer(), nullable=True))
    op.drop_column('job_log', 'status_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('status_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('job_log', 'status_type1')
    # ### end Alembic commands ###
