"""empty message

Revision ID: b7282af2cd5f
Revises: 
Create Date: 2018-03-12 15:24:31.192796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7282af2cd5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('logo', sa.String(length=400), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('telephone_number', sa.String(length=40), nullable=True),
    sa.Column('toll_free_number', sa.String(length=40), nullable=True),
    sa.Column('fax_number', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('sales_email', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_address'), 'company', ['address'], unique=True)
    op.create_index(op.f('ix_company_date_created'), 'company', ['date_created'], unique=False)
    op.create_index(op.f('ix_company_description'), 'company', ['description'], unique=True)
    op.create_index(op.f('ix_company_fax_number'), 'company', ['fax_number'], unique=True)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_company_sales_email'), 'company', ['sales_email'], unique=True)
    op.create_index(op.f('ix_company_telephone_number'), 'company', ['telephone_number'], unique=True)
    op.create_index(op.f('ix_company_toll_free_number'), 'company', ['toll_free_number'], unique=True)
    op.create_index(op.f('ix_company_website'), 'company', ['website'], unique=True)
    op.create_table('file_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('col_type', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_format_order'), 'file_format', ['order'], unique=False)
    op.create_index(op.f('ix_file_format_title'), 'file_format', ['title'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_confirmed_at'), 'user', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_date_uploaded'), 'history', ['date_uploaded'], unique=False)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_history_date_uploaded'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_confirmed_at'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_index(op.f('ix_file_format_title'), table_name='file_format')
    op.drop_index(op.f('ix_file_format_order'), table_name='file_format')
    op.drop_table('file_format')
    op.drop_index(op.f('ix_company_website'), table_name='company')
    op.drop_index(op.f('ix_company_toll_free_number'), table_name='company')
    op.drop_index(op.f('ix_company_telephone_number'), table_name='company')
    op.drop_index(op.f('ix_company_sales_email'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_fax_number'), table_name='company')
    op.drop_index(op.f('ix_company_description'), table_name='company')
    op.drop_index(op.f('ix_company_date_created'), table_name='company')
    op.drop_index(op.f('ix_company_address'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
