"""empty message

Revision ID: ba1e78bd2c2c
Revises: 0aa00de44f95
Create Date: 2018-05-03 16:44:07.367241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1e78bd2c2c'
down_revision = '0aa00de44f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_log', 'status2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('status2', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
