"""empty message

Revision ID: c323fa815f5a
Revises: 6421ebefff8a
Create Date: 2018-05-18 11:47:03.420906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c323fa815f5a'
down_revision = '6421ebefff8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('field_type2', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_settings_field_type2'), 'settings', ['field_type2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_field_type2'), table_name='settings')
    op.drop_column('settings', 'field_type2')
    # ### end Alembic commands ###
