"""empty message

Revision ID: c8c8c17e7c82
Revises: adfe0bc1db6c
Create Date: 2018-05-03 11:28:48.414654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c8c17e7c82'
down_revision = 'adfe0bc1db6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('status_type', sa.Integer(), nullable=True))
    op.drop_column('job_log', 'status_type1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('status_type1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('job_log', 'status_type')
    # ### end Alembic commands ###
