"""add completion email column to history

Revision ID: d2c4dfe71fb8
Revises: 3cc9f19b5091
Create Date: 2019-08-07 16:35:29.681962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c4dfe71fb8'
down_revision = '3cc9f19b5091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('completion_emailed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'completion_emailed')
    # ### end Alembic commands ###
