"""empty message

Revision ID: e2975b316f3f
Revises: a352d44be54b
Create Date: 2018-04-19 14:22:19.667970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2975b316f3f'
down_revision = 'a352d44be54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_format', sa.Column('mandatory', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_format', 'mandatory')
    # ### end Alembic commands ###
