"""empty message

Revision ID: f642c1705731
Revises: 6763ef838cbc
Create Date: 2018-02-28 13:16:42.175744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f642c1705731'
down_revision = '6763ef838cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_format', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_file_format_order'), 'file_format', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_format_order'), table_name='file_format')
    op.drop_column('file_format', 'order')
    # ### end Alembic commands ###
