"""empty message

Revision ID: fc75528b17ff
Revises: e2975b316f3f
Create Date: 2018-04-19 14:43:37.270644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc75528b17ff'
down_revision = 'e2975b316f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_format', 'mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_format', 'mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
